matrix:
- name: Markdown
  aspell:
    ignore-case: true
    lang: en
  dictionary:
    encoding: utf-8
    wordlists:
      - .github/wordlist.txt
  pipeline:
    - pyspelling.filters.url:
    - pyspelling.filters.markdown:
  sources:
    - '**/*.md'
    - '!**/BenchmarkDotNet.Artifacts/**/*.md'
  default_encoding: utf-8
