rules:
  anonymous-definition:
    disable: true
  concurrency-limits:
    disable: true
  dependabot-cooldown:
    config:
      days: 3
  secrets-outside-env:
    disable: true
  undocumented-permissions:
    disable: true
