os: Visual Studio 2017

# Build script
build_script:
  - ps: .\build.ps1

# Tests
test: off

artifacts:
  - path: artifacts\nuget-package\*.nupkg

environment:
  # Skip dotnet package caching on build servers
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true