os: Visual Studio 2019

# Build script
build_script:
  - ps: .\build.ps1

# Tests
test: off

artifacts:
  - path: artifacts\nuget-package\*.nupkg
  - path: artifacts\nuget-package\*.snupkg

environment:
  # Skip dotnet package caching on build servers
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
