os: Visual Studio 2022

# Build script
build_script:
  - ps: .\build.ps1

# Tests
test: off

artifacts:
  - path: artifacts\nuget-package\*.nupkg
  - path: artifacts\nuget-package\*.snupkg

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
