#:sdk Cake.Sdk
#:package Cake.FileHelpers
#:package Newtonsoft.Json
#:property ProjectType=Test
#:property SignAssembly=false
#:property XunitAutoGeneratedEntryPoint=false

///////////////////////////////////////////////////////////////////////////////
// ARGUMENTS
///////////////////////////////////////////////////////////////////////////////

var target = Argument<string>("target", "Default");
var configuration = Argument<string>("configuration", "Release");

///////////////////////////////////////////////////////////////////////////////
// GLOBAL VARIABLES
///////////////////////////////////////////////////////////////////////////////

var projectName = "Polly";

var solutions = GetFiles("./**/*.slnx");
var solutionPaths = solutions.Select(solution => solution.GetDirectory());

var srcDir = Directory("./src");
var artifactsDir = Directory("./artifacts");
var testResultsDir = System.IO.Path.Combine(artifactsDir, Directory("test-results"));

// NuGet
var nupkgDestDir = System.IO.Path.Combine(artifactsDir, Directory("package"), Directory("release"));

// Coverage reports
var coverageDir = System.IO.Path.Combine(artifactsDir, Directory("coverage"));
var coverageReportsDir = System.IO.Path.Combine(artifactsDir, Directory("coverage-reports"));

// Stryker / Mutation Testing
var strykerConfig = MakeAbsolute(File("./eng/stryker-config.json"));
var strykerOutput = MakeAbsolute(Directory(System.IO.Path.Combine(artifactsDir, Directory("mutation-report"))));

///////////////////////////////////////////////////////////////////////////////
// SETUP / TEARDOWN
///////////////////////////////////////////////////////////////////////////////

Setup(_ =>
{
    Information("");
    Information("----------------------------------------");
    Information("Starting the cake build script");
    Information("Building: " + projectName);
    Information("----------------------------------------");
    Information("");
});

Teardown(_ =>
{
    Information("Finished running tasks.");
});

//////////////////////////////////////////////////////////////////////
// PRIVATE TASKS
//////////////////////////////////////////////////////////////////////

Task("__Clean")
    .Does(() =>
{
    if (Environment.GetEnvironmentVariable("GITHUB_ACTIONS") == "true")
    {
        // Nothing to clean in CI
        return;
    }

    CleanDirectories(
    [
        testResultsDir,
        nupkgDestDir,
        artifactsDir,
        strykerOutput
    ]);

    foreach (var path in solutionPaths)
    {
        Information("Cleaning {0}", path);

        var dotNetCleanSettings = new DotNetCleanSettings
        {
            Verbosity = DotNetVerbosity.Minimal,
        };

        DotNetClean(path.ToString(), dotNetCleanSettings);
    }
});

Task("__RestoreNuGetPackages")
    .Does(() =>
{
    foreach (var solution in solutions)
    {
        Information("Restoring NuGet Packages for {0}", solution);
        DotNetRestore(solution.ToString());
    }
});

Task("__BuildSolutions")
    .Does(() =>
{
    foreach (var solution in solutions)
    {
        Information("Building {0}", solution);

        var dotNetBuildSettings = new DotNetBuildSettings
        {
            Configuration = configuration,
            Verbosity = DotNetVerbosity.Minimal,
            NoRestore = true,
            MSBuildSettings = new DotNetMSBuildSettings
            {
                TreatAllWarningsAs = MSBuildTreatAllWarningsAs.Error,
            },
        };

        DotNetBuild(solution.ToString(), dotNetBuildSettings);
    }
});

Task("__ValidateAot")
    .Does(() =>
{
    var aotProject = MakeAbsolute(File("./test/Polly.AotTest/Polly.AotTest.csproj"));
    var settings = new DotNetPublishSettings
    {
        Configuration = configuration,
        Verbosity = DotNetVerbosity.Minimal,
        MSBuildSettings = new DotNetMSBuildSettings
        {
            TreatAllWarningsAs = MSBuildTreatAllWarningsAs.Error,
        },
    };

    DotNetPublish(aotProject.ToString(), settings);
});

Task("__RunTests")
    .Does(() =>
{
    var projects = GetFiles("./test/**/*{Tests,Specs}.csproj");

    foreach (var proj in projects)
    {
        var projectName = proj.GetFilenameWithoutExtension().ToString();

        DotNetTest(proj.FullPath, new DotNetTestSettings
        {
            Configuration = configuration,
            NoBuild = true,
            ToolTimeout = System.TimeSpan.FromMinutes(10),
        });
    }
});

Task("__GenerateCoverageReports")
    .IsDependentOn("__RunTests")
    .Does(() =>
{
    var projects = GetFiles("./test/**/*{Tests,Specs}.csproj");
    var isGitHubActions = Environment.GetEnvironmentVariable("GITHUB_ACTIONS") == "true";
    var outputMarkdown = isGitHubActions && !string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("GITHUB_SHA"));
    var stepSummary = Environment.GetEnvironmentVariable("GITHUB_STEP_SUMMARY");

    foreach (var proj in projects)
    {
        var projectName = proj.GetFilenameWithoutExtension().ToString();
        var projectCoverageDir = System.IO.Path.Combine(coverageDir, projectName);

        if (!DirectoryExists(projectCoverageDir))
        {
            continue;
        }

        var coverageFiles = GetFiles(System.IO.Path.Combine(projectCoverageDir, "coverage.*.xml"));

        if (!coverageFiles.Any())
        {
            continue;
        }

        var targetDirectory = System.IO.Path.Combine(coverageReportsDir, projectName);

        foreach (var coverageFile in coverageFiles.OrderBy((file) => file.FullPath))
        {
            var tag = coverageFile.GetFilenameWithoutExtension().ToString()["coverage.".Length..];

            var reportTypes = "Cobertura;HTML";

            if (outputMarkdown)
            {
                reportTypes += ";MarkdownSummaryGitHub";
            }

            Information("Generating coverage report for {0} ({1})", projectName, tag);

            var args = $"reportgenerator -reports:\"{coverageFile}\" -targetdir:\"{targetDirectory}\" -reporttypes:{reportTypes} -tag:{tag} -title:\"{projectName}\" -verbosity:Warning";

            var result = StartProcess("dotnet", args);

            if (result != 0)
            {
                throw new InvalidOperationException($"Failed to generate the coverage report for '{projectName}' ({tag}).");
            }

            if (outputMarkdown)
            {
                var markdownSummaryFile = System.IO.Path.Combine(targetDirectory, "SummaryGithub.md");

                if (!string.IsNullOrWhiteSpace(stepSummary) && System.IO.File.Exists(markdownSummaryFile))
                {
                    var markdownSummaryPrefix = $"<details><summary>:chart_with_upwards_trend: <b>{projectName} Code Coverage report</b> ({tag})</summary>";
                    const string MarkdownSummarySuffix = "</details>";

                    var summaryContent = string.Join(
                        System.Environment.NewLine,
                        markdownSummaryPrefix,
                        string.Empty,
                        string.Empty,
                        System.IO.File.ReadAllText(markdownSummaryFile),
                        string.Empty,
                        string.Empty,
                        MarkdownSummarySuffix);

                    AppendAllLinesWithRetry(stepSummary, [summaryContent]);
                }
            }
        }
    }
});

Task("__VerifyCoverageThresholds")
    .IsDependentOn("__RunTests")
    .Does(() =>
{
    var projects = GetFiles("./test/**/*{Tests,Specs}.csproj");
    var violations = new List<string>();

    foreach (var proj in projects)
    {
        var thresholds = GetCoverageThresholds(proj.FullPath);

        if (thresholds.Count == 0)
        {
            continue;
        }

        var projectName = proj.GetFilenameWithoutExtension().ToString();
        var assemblyName = GetCoverageAssemblyName(projectName);
        var projectCoverageDir = System.IO.Path.Combine(coverageDir, projectName);

        if (!DirectoryExists(projectCoverageDir))
        {
            continue;
        }

        var coverageFiles = GetFiles(System.IO.Path.Combine(projectCoverageDir, "coverage.*.xml"));

        foreach (var coverageFile in coverageFiles.OrderBy((file) => file.FullPath))
        {
            var tag = coverageFile.GetFilenameWithoutExtension().ToString()["coverage.".Length..];
            var coverage = GetAssemblyCoverage(coverageFile.FullPath, assemblyName);

            if (coverage is null)
            {
                violations.Add($"{projectName} ({tag}): no coverage data was found for assembly '{assemblyName}'.");
                continue;
            }

            foreach (var (type, required) in thresholds)
            {
                var actual = type switch
                {
                    "line" => coverage.Value.Line,
                    "branch" => coverage.Value.Branch,
                    "method" => coverage.Value.Method,
                    _ => throw new InvalidOperationException($"Unsupported <ThresholdType> value '{type}'.")
                };

                if (actual < required)
                {
                    violations.Add($"{projectName} ({tag}): {type} coverage of {actual:0.##}% for '{assemblyName}' is below the required threshold of {required}%.");
                }
            }
        }
    }

    if (violations.Count > 0)
    {
        foreach (var violation in violations)
        {
            Error(violation);
        }

        throw new InvalidOperationException($"{violations.Count} coverage threshold violation(s) found. See the errors above.");
    }
});

Task("__CreateNuGetPackages")
    .Does(() =>
{
    var dotNetPackSettings = new DotNetPackSettings
    {
        Configuration = configuration,
        NoBuild = true,
        OutputDirectory = nupkgDestDir,
        MSBuildSettings = new DotNetMSBuildSettings
        {
            TreatAllWarningsAs = MSBuildTreatAllWarningsAs.Error,
        },
    };

    string[] packages =
    [
        System.IO.Path.Combine(srcDir, "Polly.Core", "Polly.Core.csproj"),
        System.IO.Path.Combine(srcDir, "Polly", "Polly.csproj"),
        System.IO.Path.Combine(srcDir, "Polly.RateLimiting", "Polly.RateLimiting.csproj"),
        System.IO.Path.Combine(srcDir, "Polly.Extensions", "Polly.Extensions.csproj"),
        System.IO.Path.Combine(srcDir, "Polly.Testing", "Polly.Testing.csproj"),
    ];

    Information("Building NuGet packages");

    foreach (string project in packages)
    {
        DotNetPack(project, dotNetPackSettings);
    }
});

Task("__ValidateDocs")
    .Does(() =>
{
    var result = StartProcess("dotnet", "mdsnippets --validate-content");
    if (result != 0)
    {
        throw new InvalidOperationException($"Failed to validate the documentation snippets. Are the links correct?");
    }
});

Task("__Setup")
    .IsDependentOn("__Clean")
    .IsDependentOn("__RestoreNuGetPackages");

Task("__CommonBuild")
    .IsDependentOn("__Setup")
    .IsDependentOn("__ValidateDocs")
    .IsDependentOn("__BuildSolutions");

//////////////////////////////////////////////////////////////////////
// BUILD TASKS
//////////////////////////////////////////////////////////////////////

Task("Build")
    .IsDependentOn("__CommonBuild")
    .IsDependentOn("__ValidateAot")
    .IsDependentOn("__RunTests")
    .IsDependentOn("__GenerateCoverageReports")
    .IsDependentOn("__VerifyCoverageThresholds")
    .IsDependentOn("__CreateNuGetPackages");

///////////////////////////////////////////////////////////////////////////////
// PRIMARY TARGETS
///////////////////////////////////////////////////////////////////////////////

Task("Default")
    .IsDependentOn("Build");

///////////////////////////////////////////////////////////////////////////////
// MUTATION TESTING TARGETS
///////////////////////////////////////////////////////////////////////////////

Task("MutationTestsCore")
    .IsDependentOn("__Setup")
    .Does((_) =>
{
    RunMutationTests(File("./src/Polly.Core/Polly.Core.csproj"), File("./test/Polly.Core.Tests/Polly.Core.Tests.csproj"));
});

Task("MutationTestsRateLimiting")
    .IsDependentOn("__Setup")
    .Does((_) =>
{
    RunMutationTests(File("./src/Polly.RateLimiting/Polly.RateLimiting.csproj"), File("./test/Polly.RateLimiting.Tests/Polly.RateLimiting.Tests.csproj"));
});

Task("MutationTestsExtensions")
    .IsDependentOn("__Setup")
    .Does((_) =>
{
    RunMutationTests(File("./src/Polly.Extensions/Polly.Extensions.csproj"), File("./test/Polly.Extensions.Tests/Polly.Extensions.Tests.csproj"));
});

Task("MutationTestsTesting")
    .IsDependentOn("__Setup")
    .Does((_) =>
{
    RunMutationTests(File("./src/Polly.Testing/Polly.Testing.csproj"), File("./test/Polly.Testing.Tests/Polly.Testing.Tests.csproj"));
});

Task("MutationTestsLegacy")
    .IsDependentOn("__Setup")
    .Does((_) =>
{
    RunMutationTests(File("./src/Polly/Polly.csproj"), File("./test/Polly.Specs/Polly.Specs.csproj"));
});

Task("MutationTests")
    .IsDependentOn("MutationTestsCore")
    .IsDependentOn("MutationTestsRateLimiting")
    .IsDependentOn("MutationTestsExtensions")
    .IsDependentOn("MutationTestsTesting")
    .IsDependentOn("MutationTestsLegacy");

///////////////////////////////////////////////////////////////////////////////
// EXECUTION
///////////////////////////////////////////////////////////////////////////////

await RunTargetAsync(target);

//////////////////////////////////////////////////////////////////////
// HELPER FUNCTIONS
//////////////////////////////////////////////////////////////////////

List<(string Type, double Required)> GetCoverageThresholds(string csprojPath)
{
    var thresholdRaw = XmlPeek(csprojPath, "/Project/PropertyGroup/Threshold/text()", new XmlPeekSettings { SuppressWarning = true });

    if (string.IsNullOrWhiteSpace(thresholdRaw))
    {
        return [];
    }

    var thresholdTypeRaw = XmlPeek(csprojPath, "/Project/PropertyGroup/ThresholdType/text()", new XmlPeekSettings { SuppressWarning = true });

    var types = string.IsNullOrWhiteSpace(thresholdTypeRaw)
        ? ["line", "branch", "method"]
        : thresholdTypeRaw.Split(',').Select((type) => type.Trim()).ToArray();

    var values = thresholdRaw.Split(',').Select((value) => double.Parse(value.Trim(), System.Globalization.CultureInfo.InvariantCulture)).ToArray();

    // Mirrors coverlet's Threshold parsing: when fewer values are supplied than types, the last value is reused for the remaining types.
    return [.. types.Select((type, index) => (type, values[Math.Min(index, values.Length - 1)]))];
}

string GetCoverageAssemblyName(string projectName) => projectName switch
{
    _ when projectName.EndsWith(".Tests", StringComparison.Ordinal) => projectName[..^".Tests".Length],
    _ when projectName.EndsWith(".Specs", StringComparison.Ordinal) => projectName[..^".Specs".Length],
    _ => projectName
};

(double Line, double Branch, double Method)? GetAssemblyCoverage(string coberturaPath, string assemblyName)
{
    var doc = System.Xml.Linq.XDocument.Load(coberturaPath);
    var package = doc.Descendants("package").FirstOrDefault((p) => (string?)p.Attribute("name") == assemblyName);

    if (package is null)
    {
        return null;
    }

    var line = (double)package.Attribute("line-rate")! * 100;
    var branch = (double)package.Attribute("branch-rate")! * 100;

    var methods = package.Descendants("method").ToList();
    var method = methods.Count == 0
        ? 100
        : methods.Count((m) => (double)m.Attribute("line-rate")! > 0) * 100.0 / methods.Count;

    return (line, branch, method);
}

void AppendAllLinesWithRetry(string path, IEnumerable<string> lines)
{
    var attempt = 0;

    while (attempt < 3)
    {
        try
        {
            System.IO.File.AppendAllLines(path, lines);
            break;
        }
        catch (System.IO.IOException)
        {
            attempt++;
            System.Threading.Thread.Sleep(1_000);
        }
    }
}

string PatchStrykerConfig(string path, Action<Newtonsoft.Json.Linq.JObject> patch)
{
    var json = System.IO.File.ReadAllText(path);
    var config = Newtonsoft.Json.Linq.JObject.Parse(json);

    patch(config.Value<Newtonsoft.Json.Linq.JObject>("stryker-config")!);

    // Create a new file to avoid polluting the Git tree
    var tempPath = System.IO.Path.GetTempFileName();
    tempPath = System.IO.Path.ChangeExtension(tempPath, "json");

    System.IO.File.WriteAllText(tempPath, config.ToString());

    return tempPath;
}

void RunMutationTests(FilePath target, FilePath testProject)
{
    var mutationScore = XmlPeek(target, "/Project/PropertyGroup/MutationScore/text()", new XmlPeekSettings { SuppressWarning = true });
    var score = int.Parse(mutationScore);
    var targetFileName = target.GetFilename();
    var isGitHubActions = Environment.GetEnvironmentVariable("GITHUB_ACTIONS") == "true";
    var dashboardUrl = string.Empty;
    var moduleName = target.GetFilenameWithoutExtension().ToString();
    var strykerConfigPath = strykerConfig.FullPath;

    if (moduleName == "Polly.Testing")
    {
        strykerConfigPath = PatchStrykerConfig(strykerConfigPath, (config) => config.Remove("ignore-mutations"));
    }

    if (isGitHubActions &&
        !string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("STRYKER_DASHBOARD_API_KEY")))
    {
        var projectName = $"github.com/{Environment.GetEnvironmentVariable("GITHUB_REPOSITORY")}";
        var version = Environment.GetEnvironmentVariable("GITHUB_REF_NAME");

        dashboardUrl = $"https://dashboard.stryker-mutator.io/reports/{projectName}/{version}#mutant/{moduleName}";

        strykerConfigPath = PatchStrykerConfig(strykerConfigPath, (config) =>
        {
            var reporters = config.Value<Newtonsoft.Json.Linq.JArray>("reporters")!;
            reporters.Add("dashboard");

            config["reporters"] = reporters;
            config["project-info"] = new Newtonsoft.Json.Linq.JObject
            {
                ["module"] = moduleName,
                ["name"] = projectName,
                ["version"] = version
            };
        });

        Information("Configured Stryker dashboard.");
        Information($"Mutation report will be available at {dashboardUrl}");
    }

    Information($"Running mutation tests for '{targetFileName}'. Test Project: '{testProject}'");

    var args = $"stryker --project {targetFileName} --test-project {testProject.GetFilename()} --break-at {score} --config-file {strykerConfigPath} --output {strykerOutput}/{targetFileName}";

    var testProjectDir = testProject.GetDirectory();
    var result = StartProcess("dotnet", new ProcessSettings
    {
        Arguments = args,
        WorkingDirectory = testProjectDir.FullPath,
    });

    if (result != 0)
    {
        throw new InvalidOperationException($"The mutation testing of '{targetFileName}' project failed.");
    }

    var stepSummary = Environment.GetEnvironmentVariable("GITHUB_STEP_SUMMARY");
    var markdownSummary = System.IO.Path.Combine(
        strykerOutput.FullPath,
        targetFileName.ToString(),
        "reports",
        "mutation-report.md");

    if (!string.IsNullOrWhiteSpace(stepSummary) && System.IO.File.Exists(markdownSummary))
    {
        var markdown = System.IO.File.ReadAllText(markdownSummary);

        if (!string.IsNullOrWhiteSpace(dashboardUrl))
        {
            markdown += $"\n\n## Mutation Dashboard\n\n[View Mutation Report :notebook:]({dashboardUrl})";
        }

        System.IO.File.WriteAllText(stepSummary, markdown);
    }
}
