name: 💡 Feature request
description: Suggest a feature request or improvement
title: '[Feature request]: '
labels: ['feature suggestion']
body:
- type: markdown
  attributes:
    value: |
      Please check for an existing issue and our documentation at [pollydocs.org](https://www.pollydocs.org/) before submitting a feature request.
- type: textarea
  attributes:
    label: Is your feature request related to a specific problem? Or an existing feature?
    description: A clear and concise description of what the problem is. Motivating examples help us prioritize things.
    placeholder: I am trying to do [...] but [...]
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: |
      A clear and concise description of what you want to happen. Include any alternative solutions you've considered.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: |
      Add any other context or screenshots about the feature request here.
  validations:
    required: false
