// Stryker mutation testing skips auto-generated files (those with <auto-generated> headers),
// which causes the mutated assembly to lose its AssemblyVersion. This file ensures the
// version is preserved. The SDK-generated attribute is disabled via Library.targets.
[assembly: System.Reflection.AssemblyVersion("8.0.0.0")]
