namespace Polly.Hedging;

#pragma warning disable CA1815 // Override equals and operator equals on value types

/// <summary>
/// Represents arguments used in the hedging resilience strategy.
/// </summary>
/// <typeparam name="TResult">The type of the result.</typeparam>
/// <remarks>
/// Always use the constructor when creating this struct, otherwise we do not guarantee binary compatibility.
/// </remarks>
public readonly struct HedgingActionGeneratorArguments<TResult>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="HedgingActionGeneratorArguments{TResult}"/> struct.
    /// </summary>
    /// <param name="primaryContext">The primary resilience context.</param>
    /// <param name="actionContext">
    /// The context that will be passed to action generated by <see cref="HedgingStrategyOptions{TResult}.HedgingActionGenerator"/>.
    /// .</param>
    /// <param name="attemptNumber">The zero-based hedging attempt number.</param>
    /// <param name="callback">The callback passed to hedging strategy.</param>
    public HedgingActionGeneratorArguments(
        ResilienceContext primaryContext,
        ResilienceContext actionContext,
        int attemptNumber,
        Func<ResilienceContext, ValueTask<Outcome<TResult>>> callback)
    {
        PrimaryContext = primaryContext;
        ActionContext = actionContext;
        AttemptNumber = attemptNumber;
        Callback = callback;
    }

    /// <summary>
    /// Gets the primary resilience context.
    /// </summary>
    public ResilienceContext PrimaryContext { get; }

    /// <summary>
    /// Gets the context that will be passed to action generated by <see cref="HedgingStrategyOptions{TResult}.HedgingActionGenerator"/>.
    /// </summary>
    /// <remarks>
    /// This context is cloned from <see cref="PrimaryContext"/>.
    /// </remarks>
    public ResilienceContext ActionContext { get; }

    /// <summary>
    /// Gets the zero-based hedging attempt number.
    /// </summary>
    public int AttemptNumber { get; }

    /// <summary>
    /// Gets the callback passed to hedging strategy.
    /// </summary>
    public Func<ResilienceContext, ValueTask<Outcome<TResult>>> Callback { get; }
}
