name: dependency-review

on:
  pull_request:

permissions: {}

jobs:
  dependency-review:
    runs-on: ubuntu-24.04
    if: github.event.repository.fork == false

    permissions:
      contents: read

    steps:

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          filter: 'tree:0'
          persist-credentials: false
          show-progress: false

      - name: Review dependencies
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          allow-licenses: 'Apache-2.0,BSD-3-Clause,MIT'
