name: github-pages

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:

  build-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: read

    steps:

    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Lint Markdown files
      uses: DavidAnson/markdownlint-cli2-action@ce4853d43830c74c1753b39f3cf40f71c2031eb9 # v23.0.0
      with:
        config: '.markdownlint.json'
        globs: |
          **/*.md
          !**/BenchmarkDotNet.Artifacts/**/*.md

    - name: Spellcheck
      uses: rojopolis/spellcheck-github-actions@e3cd8e9aec4587ec73bc0e60745aafd45c37aa2e # v0.60.0
      with:
        config_path: .github/spellcheck.yml

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0

    - name: Generate documentation
      run: |
        dotnet tool restore
        dotnet build --configuration Release /p:SKIP_POLLY_ANALYZERS=true
        dotnet docfx docs/docfx.json

    - name: Publish documentation
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: docs
        path: docs/_site
        if-no-files-found: error

  publish-docs:
    needs: [ build-docs ]
    runs-on: ubuntu-latest
    if: |
      github.event.repository.fork == false &&
      github.ref_name == github.event.repository.default_branch

    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: false

    permissions:
      contents: write
      pages: write

    steps:

    - name: Download documentation
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: docs
        path: docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
        cname: www.pollydocs.org
