name: Polly CI/CD Pipeline

on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    name: CI
    runs-on: windows-latest
    strategy:
      matrix: 
        build-configuration: [ Debug, Release ]
    env:
      SOLUTION_PATH: src/Polly.sln
      BUILD_CONFIGURATION: ${{ matrix.build-configuration }}
    steps:
      - name: Setup MSBuild
        id: setup_msbuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install .NET Framework 1.1
        id: instal_dotnet11
        shell: pwsh
        run: |
          choco install dotnetcore --version=1.1.2 -y

      - name: Checkout repository
        id: checkout_repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Clean .NET cache
        id: clean_dotnet_cache
        run: |
          dotnet clean $env:SOLUTION_PATH
          dotnet nuget locals all --clear

      - name: Run NuGet restore
        id: run_nuget_restore
        shell: pwsh
        run: |
          nuget restore $env:SOLUTION_PATH

      - name: Build solution
        id: build_solution
        shell: pwsh
        run: |
          msbuild $env:SOLUTION_PATH `
          /p:Configuration=$env:BUILD_CONFIGURATION

      - if: matrix.build-configuration == 'Release'
        name: Run unit tests
        id: run_unit_tests
        continue-on-error: true
        shell: pwsh
        run: |
          dotnet test $env:SOLUTION_PATH

# Built with ❤ by [Pipeline Foundation](https://pipeline.foundation)