name: ossf-scorecard

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 8 * * MON'
  workflow_dispatch:

permissions: read-all # zizmor: ignore[excessive-permissions] Recommended permissions for OSSF Scorecard

jobs:
  analysis:
    name: analysis
    runs-on: ubuntu-24.04
    if: github.event.repository.fork == false

    permissions:
      id-token: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          filter: 'tree:0'
          persist-credentials: false
          show-progress: false

      - name: Run analysis
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc # v2.4.4
        with:
          publish_results: true
          results_file: results.sarif
          results_format: sarif

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: SARIF
          path: results.sarif
          retention-days: 5

      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        with:
          sarif_file: results.sarif
