name: stale

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  stale:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false

    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@5f858e3efba33a5ca4407a664cc011ad407f2008 # v10.1.0
        with:
          days-before-close: 14
          days-before-stale: 60
          exempt-issue-labels: 'ANNOUNCEMENT,keep-open,up-for-grabs'
          stale-issue-label: 'stale'
          stale-issue-message: "This issue is stale because it has been open for 60 days with no activity. It will be automatically closed in 14 days if no further updates are made."
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
          exempt-pr-labels: 'keep-open'
          stale-pr-label: 'stale'
          stale-pr-message: "This pull request is stale because it has been open for 60 days with no activity. It will be automatically closed in 14 days if no further changes are made."
          close-pr-message: "This pull request was closed because it has been inactive for 14 days since being marked as stale."
