name: stale

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

permissions:
  issues: read
  pull-requests: read

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@1160a2240286f5da8ec72b1c0816ce2481aabf84 # v8.0.0
        with:
          days-before-close: 14
          days-before-stale: 60
          exempt-issue-labels: 'ANNOUNCEMENT,up-for-grabs,v8'
          stale-issue-label: 'stale'
          stale-issue-message: "This issue is stale because it has been open for 60 days with no activity. It will be automatically closed in 14 days if no further updates are made."
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
          stale-pr-label: 'stale'
          stale-pr-message: "This pull request is stale because it has been open for 60 days with no activity. It will be automatically closed in 14 days if no further changes are made."
          close-pr-message: "This pull request was closed because it has been inactive for 14 days since being marked as stale."
